"""Add custom payment

Revision ID: 489cfe7dd47b
Revises: 60a9e0c732a8
Create Date: 2025-04-23 03:28:48.320677

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '489cfe7dd47b'
down_revision = '60a9e0c732a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alies_payments_custom',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('alies', sa.String(length=255), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_alies_payments_custom_id'),
    sa.UniqueConstraint('alies', name='uq_alies_payments_custom_alies')
    )
    op.create_table('payments_history_custom',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_payments_history_custom_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments_history_custom')
    op.drop_table('alies_payments_custom')
    # ### end Alembic commands ###
