"""Add id_account for payment

Revision ID: f42f0c7e77b6
Revises: 489cfe7dd47b
Create Date: 2025-04-23 06:23:58.703474

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42f0c7e77b6'
down_revision = '489cfe7dd47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alies_payments_custom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_account', models.types.StringUUID(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alies_payments_custom', schema=None) as batch_op:
        batch_op.drop_column('id_account')

    # ### end Alembic commands ###
